### ISSUE TITLE
Windows 11 WSL local machine docker iamge not running

### ISSUE THREAD

**Issue by lenyabloko** [susumuota/kaggleenv#2]
Hi, 
I am trying to set up kaggleevnv on my WIndows 11 machine and following the opt 2.
After docker compose log I dont see the jupyter page url. Here is my logs:
~~~
jupyter-1  | Setting default cloud sdk project to
jupyter-1  | ERROR: (gcloud.config.set) The project property is set to the empty string, which is invalid.
jupyter-1  | To set your project, run:
jupyter-1  |
jupyter-1  |   $ gcloud config set project PROJECT_ID
jupyter-1  |
jupyter-1  | or to unset it, run:
jupyter-1  |
jupyter-1  |   $ gcloud config unset project
jupyter-1  | /opt/google/c2d-utils: line 295: -2: substring expression < 0
jupyter-1  | Setting default cloud sdk compute/region to
jupyter-1  | ERROR: (gcloud.config.set) You do not currently have an active account selected.
jupyter-1  | Please run:
jupyter-1  |
jupyter-1  |   $ gcloud auth login
jupyter-1  |
jupyter-1  | to obtain new credentials.
jupyter-1  |
jupyter-1  | If you have already logged in with a different account, run:
jupyter-1  |
jupyter-1  |   $ gcloud config set account ACCOUNT
jupyter-1  |
jupyter-1  | to select an already authenticated account to use.
jupyter-1  | /opt/google/c2d-utils: line 295: -2: substring expression < 0
jupyter-1  | Setting default cloud sdk dataproc/region to
jupyter-1  | Updated property [dataproc/region].
~~~

Does it require gcloud accout to run with VS Code localy?
Thank you

**Comment by lenyabloko** [comment]
Last time I run GPU image and it hanged (I guess no GPU can run on Windows 11). After I replaced the image to CPU in Dockerfile, it run all the way and shows url with tocken. However it also showed folowing error:
~~~
Config option `kernel_spec_manager_class` not recognized by `EnableServerExtensionApp`.
jupyter-1  | Extension package beatrix_jupyterlab took 7.3437s to import
jupyter-1  | A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
jupyter-1  | Extension package jupyter_server_proxy took 0.2075s to import
jupyter-1  | Extension package jupyter_server_ydoc took 0.2489s to import
jupyter-1  | Extension package jupyterlab_jupytext took 0.2323s to import
jupyter-1  | A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
jupyter-1  | A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
jupyter-1  | Extension package panel.io.jupyter_server_extension took 1.6151s to import
jupyter-1  | Enabling: dataproc_jupyter_plugin
jupyter-1  | - Writing config: /opt/conda/etc/jupyter
jupyter-1  |     - Validating dataproc_jupyter_plugin...
jupyter-1  |       dataproc_jupyter_plugin  OK
jupyter-1  |     - Extension successfully enabled.
jupyter-1  | Config option `kernel_spec_manager_class` not recognized by `EnableLabExtensionsApp`.
jupyter-1  | [W 2024-08-01 00:24:38.670 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
jupyter-1  | Config option `kernel_spec_manager_class` not recognized by `EnableServerExtensionApp`.
jupyter-1  | Extension package beatrix_jupyterlab took 7.3024s to import
jupyter-1  | A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
jupyter-1  | Extension package jupyter_server_proxy took 0.1485s to import
jupyter-1  | Extension package jupyter_server_ydoc took 0.1677s to import
jupyter-1  | Extension package jupyterlab_jupytext took 0.2647s to import
jupyter-1  | A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
jupyter-1  | A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
jupyter-1  | Extension package panel.io.jupyter_server_extension took 1.9158s to import
jupyter-1  | Enabling: jupyter_server_terminals
jupyter-1  | - Writing config: /opt/conda/etc/jupyter
jupyter-1  |     - Validating jupyter_server_terminals...
jupyter-1  |       jupyter_server_terminals  OK
jupyter-1  |     - Extension successfully enabled.
jupyter-1  | [E 2024-08-01 00:27:25.497 ServerApp] Exception while loading config file /opt/jupyter/.jupyter/jupyter_notebook_config.py
jupyter-1  |     Traceback (most recent call last):
jupyter-1  |       File "/opt/conda/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
jupyter-1  |         sock = connection.create_connection(
jupyter-1  |       File "/opt/conda/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
jupyter-1  |         for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
jupyter-1  |       File "/opt/conda/lib/python3.10/socket.py", line 955, in getaddrinfo
jupyter-1  |         for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
jupyter-1  |     socket.gaierror: [Errno -3] Temporary failure in name resolution
jupyter-1  |
jupyter-1  |     The above exception was the direct cause of the following exception:
~~~ 
and at the end it showed following localhost:8888/lab?tocken url:
~~~
jupyter-1  | [I 2024-08-01 17:21:20.322 ServerApp] Serving notebooks from local directory: /kaggle/working
jupyter-1  | [I 2024-08-01 17:21:20.322 ServerApp] Jupyter Server 2.12.5 is running at:
jupyter-1  | [I 2024-08-01 17:21:20.322 ServerApp] http://localhost:8888/lab?token=f17602458dd4b63be8264db9d95f3583958c2851737789e5
jupyter-1  | [I 2024-08-01 17:21:20.322 ServerApp]     http://127.0.0.1:8888/lab?token=f17602458dd4b63be8264db9d95f3583958c2851737789e5
jupyter-1  | [I 2024-08-01 17:21:20.323 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
jupyter-1  | [W 2024-08-01 17:21:20.326 ServerApp] No web browser found: Error('could not locate runnable browser').
jupyter-1  | [C 2024-08-01 17:21:20.326 ServerApp]
jupyter-1  |
jupyter-1  |     To access the server, open this file in a browser:
jupyter-1  |         file:///root/.local/share/jupyter/runtime/jpserver-263-open.html
jupyter-1  |     Or copy and paste one of these URLs:
jupyter-1  |         http://localhost:8888/lab?token=f17602458dd4b63be8264db9d95f3583958c2851737789e5
jupyter-1  |         http://127.0.0.1:8888/lab?token=f17602458dd4b63
be8264db9d95f3583958c2851737789e5
~~~

However, the above url is not loading even after I replaced the port 8888 to 8080:
Here is my Dockerfile:

~~~
# for CPU
# FROM gcr.io/kaggle-images/python:v109
FROM gcr.io/kaggle-images/python:latest

# apply patch to enable token and change notebook directory to /kaggle/working
# see jupyter_notebook_config.py.patch
COPY jupyter_notebook_config.py.patch /opt/jupyter/.jupyter/
RUN (cd /opt/jupyter/.jupyter/ && patch < jupyter_notebook_config.py.patch)

# add extra modules here
# RUN pip install -U pip
~~~

What I am doing wrong?
